### ISSUE TITLE
Feature request: suse at home should be opensuse at home

### ISSUE THREAD

**Issue by Roguito** [SUSE/suse-at-home#26]
For non-SUSE customers to participate in the whole Rancher Labs, SUSE evolution at home and be able to convince their respective employers or customers to adopt a SUSE contract. As it is now, it is only for existing SUSE customers and not an efficient marketing initiative, roadmap to paid SUSE engagements.

Or at least have something similar to vmware's VMUG which allows users to pay for the use of enterprise software for non-production use.

**Comment by zoopster** [comment]
Not sure I understand your point. The name may not be the greatest, but it's for ALL SUSE products, not just opensuse. Fortunately openSUSE Leap is 99.9% identical to SLE.
